# Generated by Django 5.1.3 on 2024-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_imageforcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageforcover',
            name='poster_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
