# Generated by Django 5.1.3 on 2024-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_date_shiped_order_date_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
