# Generated by Django 5.1.3 on 2024-12-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_deliverycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
